services:
  www:
    build: ./
    depends_on:
      - mysql
    container_name: symfonyUX
    restart: always
    ports:
      - "8000:8000"
    # dns:
    #   - 8.8.8.8
    volumes:
      - ./:/var/www/
    command: "symfony server:start"
    networks:
      - rr-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # Port SMTP
      - "8025:8025" # Port interface Web
    networks:
      - rr-net # Nom du réseau Docker

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SymfonyUX
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - rr-net

networks:
  rr-net:
    driver: bridge

volumes:
  db-data:
