<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5gVqPki\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5gVqPki/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5gVqPki.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5gVqPki\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5gVqPki\App_KernelDevDebugContainer([
    'container.build_hash' => '5gVqPki',
    'container.build_id' => '5357c64e',
    'container.build_time' => 1726516872,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5gVqPki');
